name: Build and deploy unified Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2 #v2 is correct but linter is wrong
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_068F3CE7B6394C1BB7C084A26A5F9811 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE36648B6F364D71AFBEC9630B6FF69E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_234ED2A454F946D99B856942D90B33E1 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 #v3 is correct but linter is wrong
        id: deploy-to-webapp
        with:
          app-name: 'stvi-marveloustestapp-7594887756'
          slot-name: 'Production'
          package: .